export *from './ClientsPage'
export * from './DashboardPage'
export * from './HomePage'
export * from './LoginPage'
export * from './ProductMenu'
export * from './ProductsPage'
export * from './RegisterPage'
export * from './UserMenu'
export * from './UserPage'
export * from './Section1'
export * from './Section2'
export * from './Section3'

